### ISSUE TITLE
Can't open open.spotify.com

### ISSUE THREAD

**Issue by rokonio** [sourav2k/spotify-adblock-linux#4]
When I go to the open.spotify.com website, I get an 'unable to connect' error. I think this is somewhat related to the firewall set up by the ad-blocker. I just want to know if there is a way to temporarily disable it.

**Comment by sourav2k** [comment]
the adblocker is active when you start spotify , once you close the spotifyglitchh application it should not have any effect on your system as the adblocker binary only runs when launched with the spotifyglitchh desktop entry/application
